### ISSUE TITLE
doc: With FlyClientIp and health check enabled - provide header

### ISSUE THREAD

**Issue by 64bit** [imbolc/axum-client-ip#15]
Hello, This is excellent library everything works as documented. 

I have an existing app running on Fly.io with health check enabled. 

I integerated `axum-client-ip` for all paths and `FlyClientIp` as source for IP.  On deployment health check didnt pass -  of course because `axum-client-ip` returns 500 when it did not see the `Fly-Client-IP` header for health check.  

Headers for health check can be configured through [`services.http_checks.headers`](https://fly.io/docs/reference/configuration/#services-http_checks)

Perhaps it would help to document this somewhere in this repo? if so, I'm happy to send another PR if you think it would help next person and this repo is right place to document it. 

Thank you

**Comment by imbolc** [comment]
Hi :) Thanks, I guess everyone experiencing the issue would end up in `FlyClientIp` extractor  docs. Feel free to extend them, let me know if you see a more suitable place.
