### ISSUE TITLE
report error

### ISSUE THREAD

**Issue by x7c7v7i87** [imbolc/axum-client-ip#4]
Hi

Router mode post incoming parameters: Extension,Query,Json 

Unable to pass the editor, if the ClientIp library is removed, it will run normally

err:
```text
Handler<_, _, _>` is not satisfied

the trait `Handler<T, S, B2>` is implemented for `Layered<L, H, T, S, B, B2>`
```

**Comment by imbolc** [comment]
Hey. You're probably have `ClientIp` extractor before `Json` in your handler params, make sure `Json` is the last one. Here's details in the [docs](https://docs.rs/axum/latest/axum/extract/index.html#the-order-of-extractors).

**Comment by x7c7v7i87** [comment]
okay,

thanks
